spring:
  datasource:
    username: root
    password: zzx3750322
    driver-class-name: com.mysql.cj.jdbc.Driver
    #时区改成亚洲的上海
    url: jdbc:mysql://localhost:3306/association?userUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  web:
    resources:
      static-locations: classpath:static/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.library.pojo
server:
  port: 8080
  servlet:
    context-path: /association

